site_name: Pretty DITA for DITA-OT
repo_url: 'https://github.com/jason-fox/fox.jason.pretty-dita'
repo_name: GitHub
pages:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Formatting Rules: format.md
theme: readthedocs
extra_css:
  - 'https://jason-fox.github.io/fox.jason.pretty-dita/dita.css'
